### ISSUE TITLE
error

### ISSUE THREAD

**Issue by xaoyaoo** [synodriver/pysilk#3]
pysilk.decode(silk, pcm, 24000)
  File "pysilk\backends\cython\_silk.pyx", line 271, in pysilk.backends.cython._silk.decode
pysilk.backends.cython._silk.SilkError: DEC_PAYLOAD_TOO_LARGE

**Comment by synodriver** [comment]
有原始文件吗？似乎是少加了什么参数

**Comment by xaoyaoo** [comment]
已经解决了，忘了当时是什么情况了
